
name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 16.20.2
      uses: actions/setup-node@v4
      with:
        node-version: 16.20.2
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present

    #  deploy:
    #    needs: build
    #    runs-on: ubuntu-latest
    #    steps:
    #      - name: Use Node.js 16.20.2
    #        uses: actions/setup-node@v4
    #        with:
    #          node-version: 16.20.2
    #          cache: 'npm'
    #      - run: npm ci
    #      - run: not used currently.  the build command updates the static folder.
